[tool.poetry]
name = "first"
version = "1.0.0"
description = ""
authors = ["ViacheslavKosh <koshelevskiy.v@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
